### ISSUE TITLE
一些样式的修改

### ISSUE THREAD

**Issue by ai977313677** [ruibaby/pinghsu-halo#9]
宽度用百分比控制，目前pingshu主题的文章页宽度感觉比较窄，针对PC，css文件（移动端没看过）：
```css
.main-content.post-page {
        /* 文章的实际宽度 */
	width: 66%;
}

.post-page {
        /* 文章最大宽度 */
	max-width: 66%; 
	padding: 130px 25px 20px;
}

/* 改变宽度会影响目录的位置 */
.directory-content {
	max-width: 66%;
}
```

博文的引用内容，我觉得应该改成斜体与其他内容做区分：
```css
blockquote {
	font-style:italic;
        /* 抄的csdn引用块的背景色，但是放这里不是很好看 */
        background: #eef0f4;
}
```

还有header的样式，我看了下，一般我是用大盒套小盒来解决这种定位问题：
```html
<div style="height: 70px;">
  <div style="width: 10%; text-align: left;">
    <a href="#">
      <img src="" alt="" width="50px" height="50px">
    </a>
  </div>

  <div style="width: 90%; text-align: right;">
    
  </div>
</div>
```
盒嵌套的代码太丑了，我看navbar-container有定位属性，而且固定了高度，所以我这样改了一下：
```css
.navbar-logo {
        /* margin-top之类的属性没动，因为动一下会改挺多东西的，所以下面的计算并不是正确的，navbar高70，img宽高50，top=20px */
	top: 20px;
}

.navbar-logo img {
        /* 方形感觉又小又丑的样子，所以我改成圆形了 */
	border-radius: 50%;
	width: 50px;
	height: 50px;
	outline: 0
}
```
页脚的RECENT POST和RECENT COMMENT感觉用处不大，可以考虑换成友链之类的。（页面页脚可以大气一点，不要作者名，就Theme is Pinghsu by Chakhsu Powered by Halo这两条，留一行放备案信息）

最后有一个问题，分享的QrCode标签失效了，可以删掉了……
